#!/bin/bash
today=$(date +%Y-%m-%d)
mkdir -p ~/NOTES/LOG 2>/dev/null
logfile=~/NOTES/LOG/$today.log
while true
do
    text=$(kdialog --textinputbox "Wachyadoin ?" | sed 's/^/  /')
    now=$(date +%H:%M:%S)
    echo " * $now" >> "$logfile"
    echo "$text" >> "$logfile";
    echo >> "$logfile";
    sleep 1800
done
